export default function LandingPage({ onLogin }) {
  const features = [
    { icon: '✦', title: 'AI Study Planner', desc: 'Generate a personalized week-by-week roadmap for any role with curated YouTube resources and tasks.' },
    { icon: '◈', title: 'Daily Interview Prep', desc: 'Practice Python, SQL, ML, DSA, and System Design with AI-generated questions, hints, and explanations.' },
    { icon: '🔥', title: 'Gamification', desc: 'Earn XP, level up, maintain streaks, and unlock achievements as you build consistent study habits.' },
    { icon: '▦', title: 'Analytics', desc: 'GitHub-style contribution grid, category breakdowns, and activity tracking to visualize your progress.' },
    { icon: '⊡', title: 'AI Scheduler', desc: 'Get a personalized 7-day schedule generated by AI based on your goal and available hours per day.' },
    { icon: '💻', title: 'Practice Tracker', desc: 'Track LeetCode and SQL problems solved. Set goals and monitor your progress toward interview readiness.' },
  ];

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      {/* Nav */}
      <nav className="landing-nav">
        <div className="landing-logo">
          <div className="logo-icon" style={{ width: 30, height: 30, background: 'linear-gradient(135deg,var(--v),var(--v3))', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✦</div>
          HabitPro
        </div>
        <button className="btn btn-primary btn-sm" onClick={onLogin}>
          Sign in with Google →
        </button>
      </nav>

      {/* Hero */}
      <section className="hero">
        <div className="hero-orb orb1" />
        <div className="hero-orb orb2" />
        <div className="hero-badge">✦ AI-Powered Learning Platform</div>
        <h1>
          Track Habits.<br />
          <span className="gradient-text">Ace Your Interview.</span>
        </h1>
        <p>The all-in-one AI-powered platform for students preparing for Software Engineering, Data Science, AI/ML, and Data roles.</p>
        <div className="hero-cta">
          <button className="btn btn-primary" style={{ fontSize: '1rem', padding: '14px 28px' }} onClick={onLogin}>
            Get Started Free →
          </button>
          <div className="stat-pills">
            <div className="stat-pill">✅ 100% Free</div>
            <div className="stat-pill">☁️ Cloud sync</div>
            <div className="stat-pill">✦ AI-powered</div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section>
        <div style={{ textAlign: 'center', padding: '0 24px 40px' }}>
          <h2 style={{ fontFamily: 'Syne', fontSize: '2rem', fontWeight: 800, marginBottom: 10 }}>Everything you need to land the job</h2>
          <p style={{ color: 'var(--t2)', maxWidth: 500, margin: '0 auto' }}>6 powerful tools to help you build habits, practice consistently, and show up prepared.</p>
        </div>
        <div className="features-grid">
          {features.map((f, i) => (
            <div key={i} className="gc feature-card fade-up" style={{ animationDelay: `${i * 0.08}s` }}>
              <div className="feature-icon">{f.icon}</div>
              <div className="feature-title">{f.title}</div>
              <p className="feature-desc">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Banner */}
      <div className="cta-banner">
        <h2>Ready to start your journey?</h2>
        <p>Join HabitPro today and build the habits that will get you hired.</p>
        <button className="btn btn-primary" onClick={onLogin}>Get Started — It's Free</button>
      </div>

      {/* Footer */}
      <footer className="landing-footer">
        <span>© 2025 HabitPro. Built for students, by students.</span>
        <span style={{ color: 'var(--v2)' }}>✦ HabitPro</span>
      </footer>
    </div>
  );
}
